const EXERCISE_DB = {
    // --- PEITO (1-99) ---
    "1": { name: "Supino Reto com Barra", group: "Peito" },
    "2": { name: "Supino Reto com Halteres", group: "Peito" },
    "3": { name: "Supino Inclinado com Barra", group: "Peito" },
    "4": { name: "Supino Inclinado com Halteres", group: "Peito" },
    "5": { name: "Supino Declinado com Barra", group: "Peito" },
    "6": { name: "Supino Declinado com Halteres", group: "Peito" },
    "7": { name: "Supino Vertical Máquina", group: "Peito" },
    "8": { name: "Crucifixo Reto com Halteres", group: "Peito" },
    "9": { name: "Crucifixo Inclinado com Halteres", group: "Peito" },
    "10": { name: "Crucifixo Máquina (Peck Deck)", group: "Peito" },
    "11": { name: "Crossover Polia Alta", group: "Peito" },
    "12": { name: "Crossover Polia Média", group: "Peito" },
    "13": { name: "Crossover Polia Baixa", group: "Peito" },
    "14": { name: "Flexão de Braço", group: "Peito" },
    "15": { name: "Flexão de Braço Declinada", group: "Peito" },
    "16": { name: "Flexão de Braço Inclinada", group: "Peito" },
    "17": { name: "Mergulho nas Paralelas (Foco Peito)", group: "Peito" },
    "18": { name: "Pullover com Halter", group: "Peito" },
    "19": { name: "Supino Floor Press", group: "Peito" },
    "20": { name: "Supino Guilhotina", group: "Peito" },

    // --- COSTAS (100-199) ---
    "100": { name: "Puxada Frontal Aberta (Pulley)", group: "Costas" },
    "101": { name: "Puxada Frontal Triângulo", group: "Costas" },
    "102": { name: "Puxada Frontal Supinada", group: "Costas" },
    "103": { name: "Puxada Atrás da Nuca", group: "Costas" },
    "104": { name: "Puxada Articulada", group: "Costas" },
    "105": { name: "Barra Fixa Pronada (Pull-up)", group: "Costas" },
    "106": { name: "Barra Fixa Supinada (Chin-up)", group: "Costas" },
    "107": { name: "Barra Fixa Neutra", group: "Costas" },
    "108": { name: "Levantamento Terra", group: "Costas" },
    "109": { name: "Remada Curvada com Barra", group: "Costas" },
    "110": { name: "Remada Curvada Supinada", group: "Costas" },
    "111": { name: "Remada Cavalinho (T-Bar)", group: "Costas" },
    "112": { name: "Remada Unilateral com Halter (Serrote)", group: "Costas" },
    "113": { name: "Remada Baixa no Cabo (Triângulo)", group: "Costas" },
    "114": { name: "Remada Baixa Aberta", group: "Costas" },
    "115": { name: "Remada Máquina", group: "Costas" },
    "116": { name: "Pulldown com Corda", group: "Costas" },
    "117": { name: "Pulldown com Barra Reta", group: "Costas" },
    "118": { name: "Face Pull", group: "Costas" },
    "119": { name: "Hiperextensão Lombar", group: "Costas" },
    "120": { name: "Good Morning", group: "Costas" },

    // --- PERNAS (200-299) ---
    "200": { name: "Agachamento Livre com Barra", group: "Pernas" },
    "201": { name: "Agachamento Smith", group: "Pernas" },
    "202": { name: "Agachamento Frontal", group: "Pernas" },
    "203": { name: "Agachamento Sumô", group: "Pernas" },
    "204": { name: "Agachamento Hack", group: "Pernas" },
    "205": { name: "Agachamento Búlgaro", group: "Pernas" },
    "206": { name: "Agachamento Goblet", group: "Pernas" },
    "207": { name: "Leg Press 45º", group: "Pernas" },
    "208": { name: "Leg Press Horizontal", group: "Pernas" },
    "209": { name: "Cadeira Extensora", group: "Pernas" },
    "210": { name: "Mesa Flexora", group: "Pernas" },
    "211": { name: "Cadeira Flexora", group: "Pernas" },
    "212": { name: "Flexora Vertical", group: "Pernas" },
    "213": { name: "Stiff com Barra", group: "Pernas" },
    "214": { name: "Stiff com Halteres", group: "Pernas" },
    "215": { name: "Levantamento Terra Romeno", group: "Pernas" },
    "216": { name: "Afundo Estático (Lunge)", group: "Pernas" },
    "217": { name: "Passada (Avanço)", group: "Pernas" },
    "218": { name: "Elevação Pélvica com Barra", group: "Pernas" },
    "219": { name: "Elevação Pélvica Máquina", group: "Pernas" },
    "220": { name: "Cadeira Abdutora", group: "Pernas" },
    "221": { name: "Cadeira Adutora", group: "Pernas" },
    "222": { name: "Panturrilha em Pé (Máquina)", group: "Pernas" },
    "223": { name: "Panturrilha Sentado (Sóleo)", group: "Pernas" },
    "224": { name: "Panturrilha no Leg Press", group: "Pernas" },
    "225": { name: "Panturrilha no Smith", group: "Pernas" },

    // --- OMBROS (300-399) ---
    "300": { name: "Desenvolvimento Militar (Barra em Pé)", group: "Ombros" },
    "301": { name: "Desenvolvimento com Halteres", group: "Ombros" },
    "302": { name: "Desenvolvimento Smith", group: "Ombros" },
    "303": { name: "Desenvolvimento Arnold", group: "Ombros" },
    "304": { name: "Desenvolvimento Máquina", group: "Ombros" },
    "305": { name: "Elevação Lateral com Halteres", group: "Ombros" },
    "306": { name: "Elevação Lateral na Polia", group: "Ombros" },
    "307": { name: "Elevação Lateral Máquina", group: "Ombros" },
    "308": { name: "Elevação Frontal com Halteres", group: "Ombros" },
    "309": { name: "Elevação Frontal com Barra", group: "Ombros" },
    "310": { name: "Elevação Frontal com Corda", group: "Ombros" },
    "311": { name: "Crucifixo Inverso com Halteres", group: "Ombros" },
    "312": { name: "Crucifixo Inverso Máquina (Voador Inverso)", group: "Ombros" },
    "313": { name: "Crucifixo Inverso Polia", group: "Ombros" },
    "314": { name: "Remada Alta com Barra", group: "Ombros" },
    "315": { name: "Remada Alta na Polia", group: "Ombros" },
    "316": { name: "Encolhimento com Barra", group: "Ombros" },
    "317": { name: "Encolhimento com Halteres", group: "Ombros" },
    "318": { name: "Encolhimento Máquina (Smith)", group: "Ombros" },
    "319": { name: "Rotação Externa (Manguito)", group: "Ombros" },
    "320": { name: "Rotação Interna (Manguito)", group: "Ombros" },

    // --- BÍCEPS (400-499) ---
    "400": { name: "Rosca Direta com Barra Reta", group: "Bíceps" },
    "401": { name: "Rosca Direta com Barra W", group: "Bíceps" },
    "402": { name: "Rosca Direta na Polia Baixa", group: "Bíceps" },
    "403": { name: "Rosca Alternada com Halteres", group: "Bíceps" },
    "404": { name: "Rosca Martelo com Halteres", group: "Bíceps" },
    "405": { name: "Rosca Martelo com Corda", group: "Bíceps" },
    "406": { name: "Rosca Scott com Barra W", group: "Bíceps" },
    "407": { name: "Rosca Scott Máquina", group: "Bíceps" },
    "408": { name: "Rosca Concentrada", group: "Bíceps" },
    "409": { name: "Rosca Inclinada (Banco 45)", group: "Bíceps" },
    "410": { name: "Rosca Aranha (Spider Curl)", group: "Bíceps" },
    "411": { name: "Rosca Inversa com Barra", group: "Bíceps" },
    "412": { name: "Rosca 21", group: "Bíceps" },
    "413": { name: "Rosca Punho (Antebraço)", group: "Bíceps" },
    "414": { name: "Rosca Zottman", group: "Bíceps" },

    // --- TRÍCEPS (500-599) ---
    "500": { name: "Tríceps Pulley com Barra Reta", group: "Tríceps" },
    "501": { name: "Tríceps Pulley com Corda", group: "Tríceps" },
    "502": { name: "Tríceps Pulley com Barra V", group: "Tríceps" },
    "503": { name: "Tríceps Testa com Barra W", group: "Tríceps" },
    "504": { name: "Tríceps Testa com Halteres", group: "Tríceps" },
    "505": { name: "Tríceps Francês Bilateral", group: "Tríceps" },
    "506": { name: "Tríceps Francês Unilateral", group: "Tríceps" },
    "507": { name: "Tríceps Coice com Halter", group: "Tríceps" },
    "508": { name: "Tríceps Coice na Polia", group: "Tríceps" },
    "509": { name: "Mergulho no Banco", group: "Tríceps" },
    "510": { name: "Mergulho Máquina", group: "Tríceps" },
    "511": { name: "Supino Fechado", group: "Tríceps" },
    "512": { name: "Paralelas (Foco Tríceps)", group: "Tríceps" },

    // --- ABDÔMEN (600-699) ---
    "600": { name: "Abdominal Supra (Chão)", group: "Abdômen" },
    "601": { name: "Abdominal Infra (Elevação de Pernas)", group: "Abdômen" },
    "602": { name: "Abdominal Remador", group: "Abdômen" },
    "603": { name: "Abdominal Cruzado (Oblíquo)", group: "Abdômen" },
    "604": { name: "Abdominal na Polia (Crunch)", group: "Abdômen" },
    "605": { name: "Abdominal Máquina", group: "Abdômen" },
    "606": { name: "Prancha Isométrica", group: "Abdômen" },
    "607": { name: "Prancha Lateral", group: "Abdômen" },
    "608": { name: "Abdominal Bicicleta", group: "Abdômen" },
    "609": { name: "Russian Twist (Giro Russo)", group: "Abdômen" },
    "610": { name: "Elevação de Pernas na Barra Fixa", group: "Abdômen" },
    "611": { name: "Abdominal Roda (Ab Wheel)", group: "Abdômen" },
    "612": { name: "Vácuo Abdominal", group: "Abdômen" },
    "613": { name: "Mountain Climber (Alpinista)", group: "Abdômen" },

    // --- CARDIO (700-799) ---
    "700": { name: "Esteira - Caminhada", group: "Cardio" },
    "701": { name: "Esteira - Trote", group: "Cardio" },
    "702": { name: "Esteira - Corrida Intensa", group: "Cardio" },
    "703": { name: "Esteira - Caminhada Inclinada", group: "Cardio" },
    "704": { name: "Bicicleta Ergométrica Vertical", group: "Cardio" },
    "705": { name: "Bicicleta Ergométrica Horizontal", group: "Cardio" },
    "706": { name: "Bicicleta de Spinning", group: "Cardio" },
    "707": { name: "Elíptico (Transport)", group: "Cardio" },
    "708": { name: "Simulador de Escada", group: "Cardio" },
    "709": { name: "Remo Indoor (Ergômetro)", group: "Cardio" },
    "710": { name: "Pular Corda", group: "Cardio" },
    "711": { name: "Polichinelos", group: "Cardio" },
    "712": { name: "Burpees", group: "Cardio" },
    "713": { name: "Box Jump (Salto na Caixa)", group: "Cardio" },
    "714": { name: "Battle Rope (Corda Naval)", group: "Cardio" },

    // --- MOBILIDADE E ALONGAMENTO (800-899) ---
    "800": { name: "Alongamento de Pescoço", group: "Mobilidade" },
    "801": { name: "Rotação de Ombros", group: "Mobilidade" },
    "802": { name: "Alongamento de Tríceps", group: "Mobilidade" },
    "803": { name: "Alongamento de Peitoral na Parede", group: "Mobilidade" },
    "804": { name: "Mobilidade de Tornozelo", group: "Mobilidade" },
    "805": { name: "Alongamento Gato e Vaca", group: "Mobilidade" },
    "806": { name: "Mobilidade de Quadril 90/90", group: "Mobilidade" },
    "807": { name: "Alongamento de Isquiotibiais", group: "Mobilidade" },
    "808": { name: "Alongamento de Quadríceps em Pé", group: "Mobilidade" },
    "809": { name: "Alongamento Borboleta (Adutores)", group: "Mobilidade" },
    "810": { name: "Pose da Criança (Child's Pose)", group: "Mobilidade" },
    "811": { name: "Cachorro Olhando para Baixo", group: "Mobilidade" },
    "812": { name: "Foam Roller - Costas", group: "Mobilidade" },
    "813": { name: "Foam Roller - Banda Iliotibial", group: "Mobilidade" },
    "814": { name: "Rotação Torácica", group: "Mobilidade" },
    "815": { name: "Agachamento Profundo (Cócoras)", group: "Mobilidade" }
};